name: random_user
description: App That Display a Random User.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
    
  flutter_riverpod: ^2.3.5
  go_router: ^7.0.0
  sqflite: ^2.2.6
  path: ^1.8.2
  path_provider: ^2.0.14
  http: ^0.13.5
  url_launcher: ^6.1.11
  connectivity_plus: ^4.0.1
  cached_network_image: ^3.2.3
  mocktail: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  sqflite_common_ffi: ^2.2.5
 

flutter:
  generate: true
  uses-material-design: true
  